# Generated by Django 5.0.3 on 2024-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population_65plus_male', models.IntegerField()),
                ('population_25to64_male', models.IntegerField()),
                ('population_15to24_male', models.IntegerField()),
                ('population_5to14_male', models.IntegerField()),
                ('population_0to4_male', models.IntegerField()),
                ('population_65plus_female', models.IntegerField()),
                ('population_25to64_female', models.IntegerField()),
                ('population_15to24_female', models.IntegerField()),
                ('population_5to14_female', models.IntegerField()),
                ('population_0to4_female', models.IntegerField()),
            ],
        ),
    ]
